version: '2'
services:
  broker:
    build: .
    image: zmq-mem-leak
    container_name: zmq-mem-leak.broker
    command: node broker.js
    environment:
      NODE_ENV: development
      BROKER_URI: 'tcp://0.0.0.0:3000'
    ports:
      - "3000:3000"

  srv:
    build: .
    image: zmq-mem-leak
    container_name: zmq-mem-leak.srv
    links:
      - broker
    command: node srv.js
    environment:
      NODE_ENV: development
      BROKER_URI: 'tcp://broker:3000'
      HEARTBEAT: 1
